"""add api_tokens

Revision ID: 212b63986ded
Revises: 66fddcb78fbc
Create Date: 2026-07-20 20:19:13.812461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '212b63986ded'
down_revision: Union[str, Sequence[str], None] = '66fddcb78fbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # `role` reuses the `org_member_role` PG enum created by the initial
    # migration (org_members.role). create_type=False so this doesn't try to
    # CREATE TYPE a second time; it also makes the downgrade below skip
    # DROP TYPE, which matters because org_members still depends on it.
    op.create_table('api_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', postgresql.ENUM('owner', 'admin', 'member', 'viewer', name='org_member_role', create_type=False), nullable=False),
    sa.Column('token_prefix', sa.String(length=32), nullable=False),
    sa.Column('token_sha256', sa.String(length=64), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_api_tokens_created_by_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_api_tokens_org_id_orgs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_tokens'))
    )
    op.create_index(op.f('ix_api_tokens_org_id'), 'api_tokens', ['org_id'], unique=False)
    op.create_index(op.f('ix_api_tokens_token_prefix'), 'api_tokens', ['token_prefix'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_tokens_token_prefix'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_org_id'), table_name='api_tokens')
    op.drop_table('api_tokens')
    # ### end Alembic commands ###
