"""initial schema

Revision ID: 8c8832ce9746
Revises: 
Create Date: 2026-05-25 11:05:58.756563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c8832ce9746'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orgs')),
    sa.UniqueConstraint('slug', name=op.f('uq_orgs_slug'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_service', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('org_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', 'viewer', name='org_member_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_org_members_org_id_orgs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_org_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_org_members')),
    sa.UniqueConstraint('org_id', 'user_id', name=op.f('uq_org_members_org_id_user_id'))
    )
    op.create_index(op.f('ix_org_members_org_id'), 'org_members', ['org_id'], unique=False)
    op.create_index(op.f('ix_org_members_user_id'), 'org_members', ['user_id'], unique=False)
    op.create_table('source_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.Enum('github', 'gitlab', 'azure_devops', name='source_provider'), nullable=False),
    sa.Column('credential_type', sa.Enum('pat', 'oauth', 'app', name='source_credential_type'), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('credential_blob', sa.LargeBinary(), nullable=False),
    sa.Column('credential_kid', sa.String(length=64), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_source_connections_org_id_orgs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_connections'))
    )
    op.create_index(op.f('ix_source_connections_org_id'), 'source_connections', ['org_id'], unique=False)
    op.create_index(op.f('ix_source_connections_provider'), 'source_connections', ['provider'], unique=False)
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('source_connection_id', sa.UUID(), nullable=False),
    sa.Column('remote_id', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('clone_url', sa.String(length=1024), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_repositories_org_id_orgs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_connection_id'], ['source_connections.id'], name=op.f('fk_repositories_source_connection_id_source_connections'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repositories')),
    sa.UniqueConstraint('org_id', 'full_name', name=op.f('uq_repositories_org_id_full_name')),
    sa.UniqueConstraint('source_connection_id', 'remote_id', name=op.f('uq_repositories_source_connection_id_remote_id'))
    )
    op.create_index(op.f('ix_repositories_org_id'), 'repositories', ['org_id'], unique=False)
    op.create_index(op.f('ix_repositories_source_connection_id'), 'repositories', ['source_connection_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('github', 'gitlab', 'azure_devops', name='webhook_source'), nullable=False),
    sa.Column('delivery_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('source_connection_id', sa.UUID(), nullable=True),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_connection_id'], ['source_connections.id'], name=op.f('fk_webhook_deliveries_source_connection_id_source_connections'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_deliveries')),
    sa.UniqueConstraint('source', 'delivery_id', name=op.f('uq_webhook_deliveries_source_delivery_id'))
    )
    op.create_index(op.f('ix_webhook_deliveries_event_type'), 'webhook_deliveries', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_source'), 'webhook_deliveries', ['source'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_source_connection_id'), 'webhook_deliveries', ['source_connection_id'], unique=False)
    op.create_table('scan_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'queued', 'running', 'succeeded', 'failed', 'cancelled', name='scan_job_status'), nullable=False),
    sa.Column('trigger', sa.Enum('manual', 'webhook', 'schedule', name='scan_trigger'), nullable=False),
    sa.Column('backend', sa.Enum('docker', 'k8s', 'inline', name='job_runner_backend'), nullable=False),
    sa.Column('backend_handle', sa.String(length=255), nullable=True),
    sa.Column('requested_ref', sa.String(length=255), nullable=False),
    sa.Column('resolved_commit_sha', sa.String(length=64), nullable=True),
    sa.Column('callback_secret', sa.String(length=128), nullable=False),
    sa.Column('syft_version', sa.String(length=64), nullable=True),
    sa.Column('grype_version', sa.String(length=64), nullable=True),
    sa.Column('grype_db_version', sa.String(length=64), nullable=True),
    sa.Column('sbom_object_key', sa.String(length=1024), nullable=True),
    sa.Column('sbom_sha256', sa.String(length=64), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_scan_jobs_org_id_orgs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_scan_jobs_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_jobs'))
    )
    op.create_index(op.f('ix_scan_jobs_org_id'), 'scan_jobs', ['org_id'], unique=False)
    op.create_index(op.f('ix_scan_jobs_repository_id'), 'scan_jobs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_scan_jobs_status'), 'scan_jobs', ['status'], unique=False)
    op.create_table('scan_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scan_on_push', sa.Boolean(), nullable=False),
    sa.Column('scan_on_pull_request', sa.Boolean(), nullable=False),
    sa.Column('cron_schedule', sa.String(length=64), nullable=True),
    sa.Column('max_runtime_seconds', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_scan_policies_org_id_orgs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_scan_policies_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_policies'))
    )
    op.create_index(op.f('ix_scan_policies_org_id'), 'scan_policies', ['org_id'], unique=False)
    op.create_index(op.f('ix_scan_policies_repository_id'), 'scan_policies', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_policies_repository_id'), table_name='scan_policies')
    op.drop_index(op.f('ix_scan_policies_org_id'), table_name='scan_policies')
    op.drop_table('scan_policies')
    op.drop_index(op.f('ix_scan_jobs_status'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_repository_id'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_org_id'), table_name='scan_jobs')
    op.drop_table('scan_jobs')
    op.drop_index(op.f('ix_webhook_deliveries_source_connection_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_source'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_event_type'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_repositories_source_connection_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_org_id'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_source_connections_provider'), table_name='source_connections')
    op.drop_index(op.f('ix_source_connections_org_id'), table_name='source_connections')
    op.drop_table('source_connections')
    op.drop_index(op.f('ix_org_members_user_id'), table_name='org_members')
    op.drop_index(op.f('ix_org_members_org_id'), table_name='org_members')
    op.drop_table('org_members')
    op.drop_table('users')
    op.drop_table('orgs')
    # ### end Alembic commands ###
